# Sesión 2 MONTÍCULOS BINARIOS

# Ejercicio 1: TAD Montículo Binario

ejercicio1: prueba1.c monticulo.o 
	gcc -g prueba1.c monticulo.o -o ejercicio1

# Ejercicio 2: Ordenación basada en montículos(heapsort)

ejercicio2: prueba2.c monticulo.o 
	gcc -g prueba2.c monticulo.o -o ejercicio2
monticulo.o: monticulo.h monticulo.c 
	gcc -c -g monticulo.c 
limpiar:
	rm *.o




